### ISSUE TITLE
Consider adding a note to README documentation 

### ISSUE THREAD

**Issue by curious-bryan** [fishtown-analytics/jaffle_shop#19]
@drewbanin, The jaffle_shop example is so helpful to get up and get started!  Thank you for this example!  Makes getting started with `dbt` so much easier!

One consideration, the dbt_ team may want to consider for this `jaffle_shop` example is adding a note or warning at the beginning of the README.md that the SQL in the models may need to be modified for the flavor of SQL on your DB before the example will work.  

Maybe, something similar to this NOTE after step 7.

> 7. Run the models:
> ```$ dbt run```
> **NOTE:** If this steps fails, it might be that you need to make small changes to the SQL in the models to adjust for the flavor of SQL of your target database.  Definitely consider this if you are using a community-contributed adapter.

I think newbies like me will definitely appreciate this heads up.  Even more important, it forces us to be immersed in the example.  Because we have to dig into the SQL models and make minor adjustments.  Like a total simulation of what the dbt modeler will be doing in real development.

So excited about dbt!

**Comment by curious-bryan** [comment]
@drewbanin, this issue might also be resolved by Jacob Mastel's forked **jaffle_shop** for project at https://github.com/jacobm001/jaffle_shop_mssql.

**Comment by clrcrl** [comment]
Hey @curious-bryan, very happy for you to submit this as a PR, thanks for the suggestion! Let me know if you need any help with getting setup with the fork etc. 👍

**Comment by clrcrl** [comment]
Fixed by #20
