### ISSUE TITLE
Lineage snow showing relationship to raw_ tables

### ISSUE THREAD

**Issue by guy-adams** [fishtown-analytics/jaffle_shop#21]
I may have misunderstood the intention here, but when run the demo project and show the lineage for stg_customers I see the depends i.e. the downstream, but not the upstream i.e. raw_customers. The compliled SQL shows that this is clearly where is it coming from. The same applies to all all stg_ tables. Am I doing something wrong?
![dbt1](https://user-images.githubusercontent.com/46963181/66900834-6d392b80-eff5-11e9-9945-3acd40f746a9.JPG)

**Comment by clrcrl** [comment]
Hey @guy-adams :wave:
This is actually a bug in the docs site: https://github.com/fishtown-analytics/dbt-docs/issues/15
