### ISSUE TITLE
Semaphore issue

### ISSUE THREAD

**Issue by dschoel** [fishtown-analytics/jaffle_shop#28]
In attempting to walk through the tutorial with Snowflake as the warehouse, I encounter the following error when running "dbt debug":

`~/dbt_sandbox/jaffle_shop % dbt debug
Running with dbt=0.15.0
dbt version: 0.15.0
python version: 3.7.5
python path: /usr/local/Cellar/dbt/0.15.0_1/libexec/bin/python3.7
os info: Darwin-19.2.0-x86_64-i386-64bit
Using profiles.yml file at /Users/David*****/.dbt/profiles.yml

Configuration:
  profiles.yml file [OK found and valid]
  dbt_project.yml file [OK found and valid]
  profile: jaffle_shop [OK found]
  target: dev [OK found]

Required dependencies:
 - git [OK found]

Connection:
  account: prec***ty***er
  user: David******
  database: TEST_DB
  schema: jaffle_shop
  warehouse: LOAD_WH
  role: SYSADMIN
  client_session_keep_alive: False
zsh: abort      dbt debug
/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))`

**Comment by drewbanin** [comment]
hey @dschoel - I think the `zsh abort` error and `semaphore` warnings are misleading here. It looks like dbt is failing in an unexpected way at the end of the `dbt debug` command. This error message happens right when dbt is trying to execute `select 1 as id` against your Snowflake database.

So, it sounds to me like dbt was somehow incorrectly installed on your machine. This is causing your operating system to terminate the `dbt debug` command. I think if you fix that problem, these other problems will go away. If you're a member of dbt Slack (slack.getdbt.com) then you can ask for help there in the support channel.

Just generally, we usually see things like this happen when `libssl` is not correctly linked in your dbt installation. It looks like you installed dbt via Homebrew - this ideally wouldn't ever happen, but we have seen a big jump in the incidence of this error corresponding to the release of macOS Catalina. It looks like that's the version of macOS that you're using here - I'll dig around for a helpful resource on the topic and send it through here if we don't hear from you in Slack :)
