### ISSUE TITLE
How do you donate to this repo?   

### ISSUE THREAD

**Issue by ran-eh** [fishtown-analytics/jaffle_shop#29]
Unless I am missing something, it does not allow outsiders to create branches.

**Comment by drewbanin** [comment]
hey @ran-eh! You'll want to submit a Pull Request via the process outlined here: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

The big idea is that we don't want to allow unauthorized contributors to make changes directly to this repo, so you can instead fork the repo, make some changes, and then open up a PR with your changes!

In general, it's always a good idea to create or comment on an issue before sending through a PR. This helps ensure that your commits can be merged before you take the time to make them! Hope this helps :)
